export const REDACT_PATHS: readonly string[] = [
  'req.headers.authorization',
  'req.headers.cookie',
  'req.headers["x-api-key"]',
  'res.headers["set-cookie"]',

  'clientId',
  'clientSecret',
  '*.clientId',
  '*.clientSecret',
  '*.*.clientId',
  '*.*.clientSecret',
  'req.brandConfig.clientId',
  'req.brandConfig.clientSecret',

  'access_token',
  'accessToken',
  '*.access_token',
  '*.accessToken',

  'email',
  'firstName',
  'lastName',
  'phone',
  'phoneMobile',
  'phoneHome',
  'phoneBusiness',
  'birthday',
  'postalCode',
  '*.email',
  '*.firstName',
  '*.lastName',
  '*.phone',
  '*.phoneMobile',
  '*.phoneHome',
  '*.phoneBusiness',
  '*.birthday',
  '*.postalCode',

  'addresses[*].address1',
  'addresses[*].address2',
  'addresses[*].postalCode',
  'addresses[*].city',
  'addresses[*].fullName',
  'addresses[*].firstName',
  'addresses[*].lastName',
  'addresses[*].phone',
  'paymentInstruments[*].paymentCard',
  '*.addresses[*].address1',
  '*.addresses[*].address2',
  '*.addresses[*].postalCode',
  '*.addresses[*].fullName',
  '*.addresses[*].phone',
  '*.paymentInstruments[*].paymentCard',
];
