export const ENVS = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  LOG_LEVEL: 'LOG_LEVEL',

  CORS_ORIGINS: 'CORS_ORIGINS',

  APP_SSM_PREFIX: 'APP_SSM_PREFIX',

  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_USERNAME: 'DB_USERNAME',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_NAME: 'DB_NAME',
  DB_SSL: 'DB_SSL',
  DB_POOL_MAX: 'DB_POOL_MAX',
  DB_IDLE_TIMEOUT_MS: 'DB_IDLE_TIMEOUT_MS',
  DB_CONNECT_TIMEOUT_MS: 'DB_CONNECT_TIMEOUT_MS',

  RENS_SLAS_CLIENT_ID: 'RENS_SLAS_CLIENT_ID',
  RENS_SLAS_CLIENT_SECRET: 'RENS_SLAS_CLIENT_SECRET',
  RENS_SHORT_CODE: 'RENS_SHORT_CODE',
  RENS_ORG_ID: 'RENS_ORG_ID',
  RENS_SITE_ID: 'RENS_SITE_ID',
  RENS_REDIRECT_URI: 'RENS_REDIRECT_URI',

  MONDOU_SLAS_CLIENT_ID: 'MONDOU_SLAS_CLIENT_ID',
  MONDOU_SLAS_CLIENT_SECRET: 'MONDOU_SLAS_CLIENT_SECRET',
  MONDOU_SHORT_CODE: 'MONDOU_SHORT_CODE',
  MONDOU_ORG_ID: 'MONDOU_ORG_ID',
  MONDOU_SITE_ID: 'MONDOU_SITE_ID',
  MONDOU_REDIRECT_URI: 'MONDOU_REDIRECT_URI',
} as const;
