export const ENVS = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  LOG_LEVEL: 'LOG_LEVEL',

  CORS_ORIGINS: 'CORS_ORIGINS',

  APP_SSM_PREFIX: 'APP_SSM_PREFIX',

  RENS_SLAS_CLIENT_ID: 'RENS_SLAS_CLIENT_ID',
  RENS_SLAS_CLIENT_SECRET: 'RENS_SLAS_CLIENT_SECRET',
  RENS_SHORT_CODE: 'RENS_SHORT_CODE',
  RENS_ORG_ID: 'RENS_ORG_ID',
  RENS_SITE_ID: 'RENS_SITE_ID',
  RENS_REDIRECT_URI: 'RENS_REDIRECT_URI',

  MONDOU_SLAS_CLIENT_ID: 'MONDOU_SLAS_CLIENT_ID',
  MONDOU_SLAS_CLIENT_SECRET: 'MONDOU_SLAS_CLIENT_SECRET',
  MONDOU_SHORT_CODE: 'MONDOU_SHORT_CODE',
  MONDOU_ORG_ID: 'MONDOU_ORG_ID',
  MONDOU_SITE_ID: 'MONDOU_SITE_ID',
  MONDOU_REDIRECT_URI: 'MONDOU_REDIRECT_URI',
} as const;
